# Generated by Django 6.0.5 on 2026-06-24 08:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0027_personalaccesstoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='org',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='org',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='org',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_orgs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='org',
            name='rejection_reason',
            field=models.TextField(blank=True, default=''),
        ),
    ]
