# Generated by Django 6.0.5 on 2026-06-24 09:03

import common.modules
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0029_approve_existing_orgs'),
    ]

    operations = [
        migrations.AddField(
            model_name='org',
            name='enabled_modules',
            field=models.JSONField(blank=True, default=common.modules.default_enabled_modules),
        ),
    ]
