# Generated by Django 6.0.5 on 2026-06-25 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0030_org_enabled_modules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfielddefinition',
            name='target_model',
            field=models.CharField(choices=[('Account', 'Account'), ('Case', 'Case'), ('Contact', 'Contact'), ('Estimate', 'Estimate'), ('Invoice', 'Invoice'), ('Lead', 'Lead'), ('LeadInteraction', 'Lead Interaction'), ('Opportunity', 'Opportunity'), ('RecurringInvoice', 'Recurring Invoice'), ('Task', 'Task')], max_length=32),
        ),
    ]
