# Generated by Django 6.0.5 on 2026-06-25 09:01

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import connection, migrations, models

from common.rls import get_disable_policy_sql, get_enable_policy_sql


def enable_rls(apps, schema_editor):
    if connection.vendor != "postgresql":
        return
    with connection.cursor() as cursor:
        cursor.execute(get_enable_policy_sql("lead_interaction"))


def disable_rls(apps, schema_editor):
    if connection.vendor != "postgresql":
        return
    with connection.cursor() as cursor:
        cursor.execute(get_disable_policy_sql("lead_interaction"))


class Migration(migrations.Migration):

    # RLS policy creation can't run inside an atomic block.
    atomic = False

    dependencies = [
        ('common', '0031_alter_customfielddefinition_target_model'),
        ('leads', '0013_lead_custom_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadInteraction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('interaction_type', models.CharField(choices=[('call', 'Call'), ('email', 'Email'), ('meeting', 'Meeting'), ('note', 'Note')], default='call', max_length=16, verbose_name='Type')),
                ('outcome', models.CharField(blank=True, max_length=64, null=True, verbose_name='Outcome')),
                ('notes', models.TextField(verbose_name='Notes')),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Occurred At')),
                ('next_follow_up', models.DateField(blank=True, null=True, verbose_name='Next Follow-up')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='leads.lead')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lead_interactions', to='common.org')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'verbose_name': 'Lead Interaction',
                'verbose_name_plural': 'Lead Interactions',
                'db_table': 'lead_interaction',
                'ordering': ('-occurred_at',),
                'indexes': [models.Index(fields=['lead', '-occurred_at'], name='lead_intera_lead_id_f17444_idx'), models.Index(fields=['org', '-occurred_at'], name='lead_intera_org_id_1b99af_idx')],
            },
        ),
        migrations.RunPython(enable_rls, reverse_code=disable_rls),
    ]
